### ISSUE TITLE
Output live

### ISSUE THREAD

**Issue by tobibaum** [blackary/streamlit-camera-input-live#4]
Hey there. do you have any ideas how to do the opposite? i.e. only stream live data out without any webcam input? that live data is for example constructed with some opencv operations?!

**Comment by blackary** [comment]
You could do something like this, where you create a container to hold the image, and then update the contents of a container in a loop.

https://discuss.streamlit.io/t/maintain-and-update-a-single-chart/47512/2?u=blackary

**Comment by tobibaum** [comment]
thanks for your quick answer!! i've been trying that implementation. the problem is, that streamlit itself does not love the `while true` parts of this solution. using a VPN to connect between your own and a remote device somehow leads to complications. for anyone facing similar problems: I solved my usecase using this demo: https://github.com/whitphx/streamlit-webrtc-example/blob/main/pages/8_media_files_streaming.py

**Comment by tobibaum** [comment]
closed

**Comment by blackary** [comment]
Oh yeah, streamlit-webrtc is a great idea
